"use client";

/**
 * What only the owner knows, as tap-to-answer choices inside the reply.
 *
 * Generated by the engine, never the model. One question at a time, most
 * decisive first; answering pauses and resumes the reply with the Next step
 * updated. Answers are editable: a saved answer shows with a change option,
 * and unanswered ones sit beside the thread as "Waiting for you".
 */
import { useState } from "react";

import { SERVER_URL, type OwnerQuestion, type ReplyCard as ReplyCardType } from "../lib/types";

export function QuestionCard({
  question,
  onAnswered,
}: {
  question: OwnerQuestion;
  onAnswered?: (updated: {
    questions: ReplyCardType["questions"];
    nextStep: ReplyCardType["nextStep"];
    housing: ReplyCardType["housing"];
    unansweredQuestions: { id: string; title: string; askedOn?: string | null }[];
  }) => void;
}) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [cleared, setCleared] = useState(false);
  const answered = cleared ? null : (question.choices.find((c) => c.id === question.answer) ?? null);
  const driveId = question.askedOn;

  async function answer(choiceId: string) {
    if (!driveId || busy) return;
    setBusy(true);
    setError(null);
    try {
      const response = await fetch(`${SERVER_URL}/api/answer`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ kind: question.kind, driveId, choice: choiceId }),
      });
      if (!response.ok) throw new Error(`The answer did not go through (${response.status}).`);
      const body = (await response.json()) as {
        questions: ReplyCardType["questions"];
        nextStep: ReplyCardType["nextStep"];
        housing: ReplyCardType["housing"];
        unansweredQuestions: { id: string; title: string; askedOn?: string | null }[];
      };
      setCleared(false);
      onAnswered?.(body);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  async function change() {
    // A wrong tap never sticks: show the choices again; the next tap
    // overwrites the saved answer and the history re-derives.
    setCleared(true);
    setError(null);
  }

  if (answered) {
    return (
      <div className="qbox" data-testid={`question-${question.kind}`} data-answered={answered.id}>
        <p>{question.question}</p>
        <div className="up mine">
          <b>You:</b> {answered.label}{" "}
          <button type="button" className="link" data-testid={`change-${question.kind}`} onClick={() => void change()}>
            change
          </button>
        </div>
        {error ? <div className="err">{error}</div> : null}
      </div>
    );
  }

  return (
    <div className="qbox open" data-testid={`question-${question.kind}`}>
      <div className="eyebrow">I need one answer</div>
      <p>{question.question}</p>
      <div className="opts">
        {question.choices.map((choice) => (
          <button
            key={choice.id}
            type="button"
            className="opt"
            data-testid={`answer-${question.kind}-${choice.id}`}
            disabled={busy}
            onClick={() => void answer(choice.id)}
          >
            {choice.label}
          </button>
        ))}
      </div>
      {error ? <div className="err">{error}</div> : null}
    </div>
  );
}
