"""Owner questions: answers in, Car history re-derived (ticket 07).

Questions are generated by the engine (`KTA.carQuestions`), never the model.
Answers are saved in SQLite (`question_answers`) and applied through engine
operations at their point in time:

* a "flashed …" answer records a Flash BEFORE the Drive it explains
  (time = the Drive's start minus a minute), so the Drive becomes the first
  one on the new Map version and the Undo can name the file to flash back;
* a "fitted a part / nothing / no" answer marks the Drive's Unexplained
  change AFTER it (the engine's `carAnswer … 'neither'` — no flash, still
  watched);
* a housing answer changes no history: it only resolves the Flash plan's own
  preset route, shown inside the KTuner box.

Then the Car history is rebuilt from events, not patched: every upload's raw
CSV in time order, every Flash in time order, every answer after its Drive —
through the worker's pure engine ops. Answering again overwrites the row and
rebuilds again. Everything persists in SQLite, so a restart keeps it.
"""

from __future__ import annotations

from typing import Any

# What each choice does. `flash` means record a Flash before the Drive with
# this map name and change; `answer` means `carAnswer` this Drive afterwards;
# `none` means history is untouched (housing, or an explicit "no").
#
# Map names keep the KTuner basemap's own spelling first: the Undo names
# "Map version 1 · Starter 21 Dual Tune 2", and the bad flash is visibly not it.
EFFECTS: dict[tuple[str, str], dict[str, Any]] = {
    ("what-changed", "maf"): {
        "flash": {"map": "Starter 21 Dual Tune 2 · MAF Scaling changed", "changed": "afm"},
    },
    ("what-changed", "other-flash"): {
        "flash": {"map": "Starter 21 Dual Tune 2 · edited", "changed": "other"},
    },
    ("what-changed", "part"): {"answer": "neither"},
    ("what-changed", "nothing"): {"answer": "neither"},
    ("did-flash", "undo"): {
        "flash": {"map": "Starter 21 Dual Tune 2", "changed": "afm"},
    },
    ("did-flash", "other"): {
        "flash": {"map": "Starter 21 Dual Tune 2 · new file", "changed": "other"},
    },
    ("did-flash", "no"): {"none": True},
    ("housing", "factory"): {"none": True},
    ("housing", "hvi"): {"none": True},
    ("housing", "race"): {"none": True},
    ("housing", "won"): {"none": True},
    ("housing", "unsure"): {"none": True},
}

VALID_KINDS = ("what-changed", "housing", "did-flash")

# The tap-to-answer choices per question, as the engine asks them
# (`KTA.carQuestions`). Kept here so an answer validates even after the loop
# moved on (the did-flash question needs the Undo open when its Drive arrived,
# not when the answer lands).
VALID_CHOICES: dict[str, tuple[str, ...]] = {
    "what-changed": ("maf", "other-flash", "part", "nothing"),
    "housing": ("factory", "hvi", "race", "won", "unsure"),
    "did-flash": ("undo", "other", "no"),
}


def question_id(kind: str, drive_id: str) -> str:
    """The stable id one answer overwrites: `what-changed:<driveId>`."""
    return f"{kind}:{drive_id}"


def effect_of(kind: str, choice: str) -> dict[str, Any]:
    """What answering does to history. Unknown pairs change nothing."""
    return EFFECTS.get((kind, choice), {"none": True})


def flash_for_question(kind: str, choice: str, drive_start: int | None, drive_id: str) -> dict[str, Any] | None:
    """The Flash a "flashed …" answer records, before the Drive it explains."""
    effect = effect_of(kind, choice)
    spec = effect.get("flash")
    if not spec or drive_start is None:
        return None
    return {
        # One flash per question: answering again overwrites it, never doubles it.
        "id": f"q-{kind}-{drive_id}",
        "time": drive_start - 60_000,
        "map": spec["map"],
        "changed": spec["changed"],
        "note": f"Owner answer on {drive_id}: {kind} → {choice}.",
    }


async def rebuild_history(store, worker, now_ms: int) -> dict[str, Any]:
    """Rebuild the Car history from events, not by patching.

    Every upload's CSV in drive-start order, every Flash in flash-time order,
    every Unexplained-change answer after its Drive — through the worker's pure
    engine ops. Returns the final engine state (also saved to SQLite).
    """
    drives = sorted(
        store.list_drives(),
        key=lambda d: (d.get("started_at") or d.get("received_at") or 0, d.get("id") or ""),
    )
    flashes = sorted(store.list_flashes(), key=lambda f: (f.get("flashed_at") or 0, f.get("id") or ""))
    legacy = store.list_answers()
    qa = store.list_question_answers()

    # Unexplained-change marks derived from question answers ("after it").
    after: dict[str, str] = {}
    for entry in qa.values():
        effect = effect_of(entry["kind"], entry["choice"])
        if effect.get("answer"):
            after[entry["drive_id"]] = effect["answer"]

    state: dict[str, Any] = {}
    applied_flash_ids: set[str] = set()

    async def apply_flash(flash: dict[str, Any]) -> None:
        nonlocal state
        if flash["id"] in applied_flash_ids:
            return
        applied_flash_ids.add(flash["id"])
        out = await worker.call(
            "recordFlash",
            state=state,
            flash={"time": flash["flashed_at"], "map": flash["map"], "changed": flash.get("changed", "other")},
            now=now_ms,
        )
        state = out["state"]

    for drive in drives:
        upload = store.get_upload(drive["upload_id"]) if drive.get("upload_id") else None
        if upload is None:
            continue
        start = drive.get("started_at")
        # Every Flash at or before this Drive's start goes in first.
        for flash in flashes:
            if start is not None and (flash.get("flashed_at") or 0) <= start:
                await apply_flash(flash)
        csv_text = upload["csv"].decode("utf-8", "replace")
        out = await worker.call(
            "ingestUpload",
            csv=csv_text,
            fileName=drive.get("file_name") or "TunerView.csv",
            now=now_ms,
            state=state,
        )
        state = out["state"]
        drive_id = out["drive"]["id"]
        # The Unexplained-change answer for this Drive, after it.
        mark = after.get(drive_id) or legacy.get(drive_id)
        if mark:
            state = (await worker.call("answerDrive", state=state, driveId=drive_id, answer=mark))["state"]

    # Flashes after the last Drive (e.g. an Undo flashed today, no drive yet).
    for flash in flashes:
        await apply_flash(flash)

    store.save_car_state(state)
    sync_map_versions(store, state)
    return state


def sync_map_versions(store, state: dict[str, Any]) -> None:
    """Keep SQLite's Map version list abreast of the engine's (names only).

    Tables stay where they are: version 1 holds the KTuner basemap's tables,
    later versions from answer flashes hold names until ticket 13 stores the
    checked change. Idempotent: existing rows are never overwritten.
    """
    versions = (state or {}).get("mapVersions") or []
    for v in versions:
        try:
            n = int(v.get("n"))
        except (TypeError, ValueError):
            continue
        if store.map_version(n) is not None:
            continue
        store.ensure_map_version(
            n,
            str(v.get("name") or "Starter 21 Dual Tune 2"),
            None,
            source="answer-flash" if n != 1 else "ktuner-basemap",
            kind=str(v.get("kind") or "flash"),
            flashed_at=v.get("from"),
            flash_id=v.get("flashId"),
            changed=v.get("changed"),
            note=str(v.get("note") or ""),
        )


def unanswered(all_questions: list[dict[str, Any]], saved: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    """The questions with no saved answer — "Waiting for you"."""
    return [q for q in all_questions if q.get("id") not in saved]


__all__ = [
    "EFFECTS",
    "VALID_CHOICES",
    "VALID_KINDS",
    "effect_of",
    "flash_for_question",
    "question_id",
    "rebuild_history",
    "sync_map_versions",
    "unanswered",
]
