#!/usr/bin/env node
// Regenerates the REF block inside engine/kta-engine.js and data/ktuner-map.js from
// data/ktuner-maps-digitized.json (the owner's digitized KTuner maps).
// Run after updating the JSON:  node tools/sync-ref.js
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const maps = JSON.parse(fs.readFileSync(path.join(root, 'data/ktuner-maps-digitized.json'), 'utf8'));

const row = (a) => '[' + a.map((n) => +n).join(',') + ']';
const grid = (g, pad) => '[\n' + g.map((r) => pad + '  ' + row(r)).join(',\n') + '\n' + pad + ']';

function need(key) {
  if (!maps[key]) throw new Error('Missing table in JSON: ' + key);
  return maps[key];
}

const maf = need('MAF_Scaling_Factory');
const block = `/* REF:BEGIN (generated by tools/sync-ref.js from data/ktuner-maps-digitized.json; do not edit by hand) */
  var REF = {
    source: 'Owner-supplied KTuner maps, digitized from screenshots. Load (column) axes were not captured, so columns are indexed from 0.',
    maf: {
      hz: ${row(maf.rpm_axis)},
      factory: ${row(maf.values[0])},
      custom: ${row(need('MAF_Scaling_Custom').values[0])},
      prl: ${row(need('MAF_Scaling_PRL_Race').values[0])},
      won27: ${row(need('MAF_Scaling_27Won_Race').values[0])}
    },
    wot: {
      rpm: ${row(need('WOT_Enrich_L').rpm_axis)},
      values: ${grid(need('WOT_Enrich_L').values, '      ')}
    },
    boost: {
      rpm: ${row(need('Boost_Target_1_Normal_L').rpm_axis)},
      normal: ${grid(need('Boost_Target_1_Normal_L').values, '      ')},
      eco: ${grid(need('Boost_Target_1_ECO_L').values, '      ')}
    },
    di: {
      unit: 'kPa',
      rpm: ${row(need('DI_Fuel_Pressure_Target_0pct').rpm_axis)},
      values: ${grid(need('DI_Fuel_Pressure_Target_0pct').values, '      ')}
    }
  };
  /* REF:END */`;

const file = path.join(root, 'engine/kta-engine.js');
const src = fs.readFileSync(file, 'utf8');
const re = /\/\* REF:BEGIN[\s\S]*?\/\* REF:END \*\//;
if (!re.test(src)) throw new Error('REF markers not found in engine/kta-engine.js');
fs.writeFileSync(file, src.replace(re, block));
console.log('REF block updated in engine/kta-engine.js');

// The whole map for the app's Map screen, as a script so index.html works from file://
// (browsers refuse to fetch a local JSON file there).
const mapFile = path.join(root, 'data/ktuner-map.js');
const header = '/* Generated by tools/sync-ref.js from data/ktuner-maps-digitized.json; do not edit by hand.\n' +
  ' * The owner\'s KTuner map (Starter 21 Dual Tune 2 base), digitized from screenshots.\n' +
  ' * Load (column) axes were not captured, so columns are indexed from 0. */\n';
const tables = {};
Object.keys(maps).forEach((k) => { tables[k] = { rpm_axis: maps[k].rpm_axis, values: maps[k].values, notes: maps[k].notes || '' }; });
fs.writeFileSync(mapFile, header + 'window.KTA_MAP = ' + JSON.stringify({ name: 'Starter 21 Dual Tune 2', tables: tables }) + ';\n');
console.log('Wrote data/ktuner-map.js (' + Object.keys(tables).length + ' tables)');

// The map-change thresholds for the browser, as a script so index.html works
// from file:// (browsers refuse to fetch a local JSON file there). Source of
// truth is data/thresholds.json; the engine reads window.KTA_THRESHOLDS.
const th = JSON.parse(fs.readFileSync(path.join(root, 'data/thresholds.json'), 'utf8'));
const thFile = path.join(root, 'data/thresholds.js');
const thHeader = '/* Generated by tools/sync-ref.js from data/thresholds.json; do not edit by hand.\n' +
  ' * Every threshold that bounds a map change (ADR 0003). */\n';
fs.writeFileSync(thFile, thHeader + 'window.KTA_THRESHOLDS = ' + JSON.stringify(th) + ';\n');
console.log('Wrote data/thresholds.js');
